apiVersion: v1
kind: ConfigMap
metadata:
  name: user-management
  labels:
    app: user-management
data:
  AUTH0_API_AUDIENCE: login
  AUTH0_ISSUER: https://dev-um95566h.auth0.com/
  POSTGRES_HOST: postgresql
  POSTGRES_PORT: "5432"
  POSTGRES_DB: fareed
  POSTGRES_USER: fareed
  POSTGRES_PASSWORD: fareed